---
title: "Tidy_Up"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# Note: Need to read in the data with `tidyverse` as that is the only way to make it availabe when knitting R markdown to HTML
library(tidyverse)
zillow_oc_2017 <- read_csv(file="../../02-Evr_Read_CSV/Resources/zillow_orange_county_2017.csv")
```

### Calculate the total square feet combining `finishedsquarefeet` & `garagetotalsqft`

```{r}
zillow_oc_2017 <- zillow_oc_2017 %>% mutate(totalsquarefeet=finishedsquarefeet + garagetotalsqft) 
```

### Calculate a summary table of statistics by zipcode

```{r}
zillow_oc_2017_summary <- zillow_oc_2017 %>% group_by(regionidzip) %>%              
                    summarize(Mean_Total_SqFt=mean(totalsquarefeet), 
                              Number_of_Homes=n(), 
                              Number_of_Pools=sum(poolcnt), 
                              Median_Bedrooms=median(bedroomcnt), 
                              Median_Bathrooms=median(bathroomcnt))
```